### PR TITLE
Add a `CODEOWNERS` file

### PR DESCRIPTION
**Pull request by mhagger**
/cc @github/git-storage

### CODE REVIEW

**Review by tgummerer — APPROVED** [review]

**Comment by Gon128** [comment]
🔥🔥

**Review by Gon128 — COMMENTED** [review]
ت

**Comment by Setarland** [comment]
Cc2149

**Comment by Setarland** [comment]
git-multimail/README.rst

**Review by Toba1984 — COMMENTED** [review]
Pengkodean owner

**Review by rashworld-max — APPROVED** [review]

**Pull request merged**
